apiVersion: v1
kind: PersistentVolume
metadata:
  name: www-root
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /var/www/wwwroot
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-conf
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /var/www/wwwroot/conf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www-root-c
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  volumeName: nginx
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  phase: Bound
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-conf-c
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: nginx-conf
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  phase: Bound